### PR TITLE
debian/control: pre install nginx

### PR DESCRIPTION
**Pull request by fredericlepied**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/27

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Review by sileht — APPROVED** [review]

**Comment by fredericlepied** [comment]
regate

**Pull request merged**
